apiVersion: v1
kind: Service
metadata:
  name: minitinder-ns-service
spec:
  selector:
    app: minitinder-ns
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30002
  type: NodePort
