apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-deployment
  labels:
    app: cassandra
spec:
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra:latest
          ports:
            - containerPort: 9042
          resources:
            limits:
              memory: 8Gi
            requests:
              memory: 4Gi
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: init-script
          emptyDir: {}
